# Week 4 Challenges

In [24]:
import pandas as pd
import numpy as np
import seaborn as sns

## Challenge 01
### 1.1 Concatenating dataframes [1 pt]

Join the following two dataframes into a single dataframe. The result should contain 4 columns, A, B, C, and D. Assign the result to to the variable `combined_dataframe`.

In [25]:
df1 = pd.DataFrame({'A': ['A0', 'A1', 'A2'],
                    'B': ['B0', 'B1', 'B2']},
                    index=['K0', 'K1', 'K2'])

df2 = pd.DataFrame({'C': ['C0', 'C1', 'C2'],
                    'D': ['D0', 'D1', 'D2']},
                    index=['K0', 'K2', 'K3'])

In [26]:
combined_dataframe = pd.concat([df1, df2], axis=1)

In [27]:
#hidden tests are within this cell
combined_dataframe

      A    B    C    D
K0   A0   B0   C0   D0
K1   A1   B1  NaN  NaN
K2   A2   B2   C1   D1
K3  NaN  NaN   C2   D2

## Challenge 02
### 2.1 Merging dataframes [1 pt]
Merge the dataframes `orders` and `customers` into one dataframe called `orders_with_names`. The resulting dataframe should contain all columns from both dataframes. Then, sort the resulting dataframe by order date (`order_date`) in ascending order.

In [28]:
orders = pd.DataFrame({
    'order_id': [1, 2, 3, 4],
    'customer_id': [101, 102, 101, 103],
    'order_date': ['2023-01-02', '2023-01-04', '2023-01-01', '2023-01-03']
})

customers = pd.DataFrame({
    'customer_id': [101, 102, 103, 104],
    'name': ['Alice', 'Rahul', 'Jing', 'David'],
    'country': ['USA', 'India', 'UK', 'Australia']
})

In [29]:
orders_with_names = pd.merge(orders, customers, on='customer_id').sort_values('order_date')

In [30]:
#hidden tests are within this cell
orders_with_names

   order_id  customer_id  order_date   name country
2         3          101  2023-01-01  Alice     USA
0         1          101  2023-01-02  Alice     USA
3         4          103  2023-01-03   Jing      UK
1         2          102  2023-01-04  Rahul   India

## Challenge 03
### 3.1 Reshaping dataframes [1 pt]
Given the following dataframe `sales_data`, reshape it so that the data is transformed from wide format to long format. The resulting dataframe should contain three columns: `date`, `product`, and `sales`. Assign the result to the variable `sales_data_melted`.

In [31]:
sales_data = pd.DataFrame({
    'date': ['2023-01-01', '2023-01-02', '2023-01-03'],
    'product_A': [100, 120, 90],
    'product_B': [150, 180, 160],
    'product_C': [80, 95, 110]
})

In [32]:
sales_data_melted = pd.melt(sales_data, id_vars=['date'], var_name='product', value_name='sales')

In [33]:
#hidden tests are within this cell
sales_data_melted

         date    product  sales
0  2023-01-01  product_A    100
1  2023-01-02  product_A    120
2  2023-01-03  product_A     90
3  2023-01-01  product_B    150
4  2023-01-02  product_B    180
5  2023-01-03  product_B    160
6  2023-01-01  product_C     80
7  2023-01-02  product_C     95
8  2023-01-03  product_C    110

## Challenge 04
### 4.1 Aggregating functions [1 pt]
For this challenge and several of the following, we will use a dataset about penguins measured in the Palmer Archipelago of the Antarctic.

In [34]:
penguins = sns.load_dataset("penguins")
penguins.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

Using pandas' aggregating functions, answer the following questions:

1. What is the average `body_mass_g` for each species? The result should be a Series with the index labeled `species`. Save this result to the variable `average_body_mass`.

2. What is the median `bill_length_mm` on each island?  The result should be a Series with the index labeled `island`. Save this result to the variable `median_bill_length`.

In [35]:
average_body_mass = penguins.groupby('species')['body_mass_g'].mean()
median_bill_length = penguins.groupby('island')['bill_length_mm'].median()

In [36]:
#hidden tests are within this cell

## Challenge 05
### 5.1 Filtering dataframes [1 pt]
Filter the dataframe penguins according to the following conditions:

1. The `species` is either `Adelie` or `Chinstrap`. Save this as `adelie_or_chinstrap`.

2. The `sex` is `Female` and the `species` is `Gentoo`. Save this as `gentoo_female`.

3. The `island` is `Dream`, the `species` is `Chinstrap`, and the penguin's `body_mass_g` is greater than 3500g. Save this as `dream_chinstrap`.

In [37]:
adelie_or_chinstrap = penguins[(penguins['species'] == 'Adelie') | (penguins['species'] == 'Chinstrap')]
gentoo_female = penguins[(penguins['sex'] == 'Female') & (penguins['species'] == 'Gentoo')]
dream_chinstrap = penguins[(penguins['island'] == 'Dream') & (penguins['species'] == 'Chinstrap') & (penguins['body_mass_g'] > 3500)]

In [38]:
#hidden tests are within this cell

## Challenge 06
### 6.1 Transforming columns [1 pt]
Using the `transform()` method in pandas, standardize the `body_mass_g` column in the `penguins` dataframe. Save the new column as `body_mass_zscore`. 

Hint: remember the formula for the z-score used in the lecture video!

In [39]:
penguins['body_mass_zscore'] = penguins['body_mass_g'].transform(lambda x: (x - x.mean()) / x.std())

In [40]:
#hidden tests are within this cell

### 6.2 Grouping and transforming [1 pt]
Using the `transform()` method, calculate the z-score for the `body_mass_g` column--but this time, within grouping by each `species` in the `penguins` dataframe (why would we want to do this? Think about what would be different about z-scores if they are computed within group, rather than pooling all the penguins). Save the new column as `body_mass_zscore_species`.

In [41]:
penguins['body_mass_zscore_species'] = penguins.groupby('species')['body_mass_g'].transform(lambda x: (x - x.mean()) / x.std())

In [42]:
#hidden tests are within this cell

## Challenge 07
### 7.1 Define a custom function for manipulating data [1 pt]
Define a function called `millimeters_to_inches` that converts millimeters to inches. The function should accept numeric datatypes. You'll need to use the fact that 1 millimeter = 0.03937 inches.

In [43]:
def millimeters_to_inches(mm):
    return mm * 0.03937

In [44]:
#hidden tests are within this cell

### 7.2 Apply a custom function to a column [1 pt]
Using the `.apply()` method, use the `millimeters_to_inches` function to convert data from the `bill_length_mm` column in the `penguins` dataframe. Save the result as a new column, `bill_length_in`.

In [45]:
penguins['bill_length_in'] = penguins['bill_length_mm'].apply(millimeters_to_inches)

In [46]:
#hidden tests are within this cell