# Module 3 Challenges

In [3]:
import pandas as pd
import seaborn as sns

## Challenge 01 

### 1.1 Create a Series [1 pt]
Create a pandas Series named `fruits` with the following elements: 'apple', 'banana', 'cherry', 'date', 'elderberry'.

In [4]:
fruits = None 

# YOUR CODE HERE
fruits = pd.Series(['apple', 'banana', 'cherry', 'date', 'elderberry'])

In [5]:
# hidden tests are within this cell
fruits

0         apple
1        banana
2        cherry
3          date
4    elderberry
dtype: str

### 1.2 Create a Series with an Index [1 pt]
Create another Series named `scores` with the following data and index:

Data: [85, 92, 78, 95, 88]

Index: ['Sonja', 'Jason', 'Sahar', 'Nelson', 'Asya']

In [6]:
scores = None
# YOUR CODE HERE
scores = pd.Series(data=[85, 92, 78, 95, 88], index=['Sonja', 'Jason', 'Sahar', 'Nelson', 'Asya'])

In [7]:
# hidden tests are within this cell
scores

Sonja     85
Jason     92
Sahar     78
Nelson    95
Asya      88
dtype: int64

### 1.3 Access elements in a Series with `.loc` [1 pt]
Access Nelson's score using `.loc` and save it to the variable `nelson_score`.

In [8]:
nelson_score = None

# YOUR CODE HERE
nelson_score = scores.loc['Nelson']

In [9]:
# hidden tests are within this cell
nelson_score

np.int64(95)

### 1.4 Access elements in a Series with `.iloc` [1 pt]
Access the score of the second person in the series using `.iloc` and save it to the variable `second_person_score`.

In [10]:
second_person_score = None 

# YOUR CODE HERE
second_person_score = scores.iloc[1]

In [11]:
# hidden tests are within this cell
second_person_score

np.int64(92)

## Challenge 02

### 2.1 Create a DataFrame [1 pt]
Create a DataFrame named `student_data` with the following columns and values:

 - Name: ['Sonja', 'Jason', 'Sahar', 'Nelson', 'Asya']
 - Age: [22, 47, 31, 19, 24]
 - Major: ['Math', 'Physics', 'Chemistry', 'Literature', 'Computer Science']
 - GPA: [3.8, 3.9, 3.7, 3.6, 4.0]

 The column names in the DataFrame should be capitalized as shown above.

In [12]:
student_data = None

# YOUR CODE HERE
student_data = pd.DataFrame({
    'Name': ['Sonja', 'Jason', 'Sahar', 'Nelson', 'Asya'],
    'Age': [22, 47, 31, 19, 24],
    'Major': ['Math', 'Physics', 'Chemistry', 'Literature', 'Computer Science'],
    'GPA': [3.8, 3.9, 3.7, 3.6, 4.0]
})

In [13]:
# hidden tests are within this cell
student_data

     Name  Age             Major  GPA
0   Sonja   22              Math  3.8
1   Jason   47           Physics  3.9
2   Sahar   31         Chemistry  3.7
3  Nelson   19        Literature  3.6
4    Asya   24  Computer Science  4.0

### 2.2 Add a new column [1 pt]
Add a column to the `student_data` called `Year` with the values [2, 2, 3, 1, 4].

In [14]:
# YOUR CODE HERE
student_data['Year'] = [2,2,3,1,4]

In [15]:
# hidden tests are within this cell
student_data

     Name  Age             Major  GPA  Year
0   Sonja   22              Math  3.8     2
1   Jason   47           Physics  3.9     2
2   Sahar   31         Chemistry  3.7     3
3  Nelson   19        Literature  3.6     1
4    Asya   24  Computer Science  4.0     4

### 2.3 Drop a column [1 pt]
Drop the column `Name` from the `student_data` DataFrame (note: this might be one step we would take towards _anonymizing_ a dataset).

In [16]:
# YOUR CODE HERE
student_data.drop(columns = ['Name'], inplace=  True)

In [17]:
# hidden tests are within this cell
student_data

   Age             Major  GPA  Year
0   22              Math  3.8     2
1   47           Physics  3.9     2
2   31         Chemistry  3.7     3
3   19        Literature  3.6     1
4   24  Computer Science  4.0     4

### 2.4 Drop a row [1 pt]
Drop the student whose index is 3 from `student_data`.

In [18]:
# YOUR CODE HERE
student_data.drop(index=3, inplace=True)

In [19]:
# hidden tests are within this cell
student_data

   Age             Major  GPA  Year
0   22              Math  3.8     2
1   47           Physics  3.9     2
2   31         Chemistry  3.7     3
4   24  Computer Science  4.0     4

## Challenge 03

### 3.1 Inspect a DataFrame for understanding [2 pts]
Read the DataFrame `penguins` by running the code in the cell below.

In [20]:
penguins = sns.load_dataset('penguins')

Calculate the following values: 

- the number of rows in `penguins` and save this as `penguin_rows`
- the number of columns in `penguins` and save this as `penguin_columns`
- the names of the columns in `penguins` and save this as `penguin_column_names`
- the first 10 rows of `penguins` and save this as `penguin_first_ten_rows`
- the second to last row of `penguins` and save this as `penultimate_penguin`

In [40]:
penguin_rows = None
penguin_columns = None
penguin_column_names = None
penguin_first_ten_rows = None
penultimate_penguin = None

# YOUR CODE HERE
penguin_rows = penguins.shape[0]
penguin_columns = penguins.shape[1]
penguin_column_names = penguins.columns
penguin_first_ten_rows = penguins.head(10)
penultimate_penguin = penguins.iloc[-2]

In [41]:
# hidden tests are within this cell
print(penguin_rows,
penguin_columns,
penguin_column_names,
penguin_first_ten_rows,
penultimate_penguin)

344 8 Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex', 'body_mass_ounces'],
      dtype='str')   species     island  bill_length_mm  bill_depth_mm  flipper_length_mm  \
0  adelie  Torgersen        39.10000           18.7              181.0
1  adelie  Torgersen        39.50000           17.4              186.0
2  adelie  Torgersen        40.30000           18.0              195.0
3  adelie  Torgersen        43.92193            NaN                NaN
4  adelie  Torgersen        36.70000           19.3              193.0
5  adelie  Torgersen        39.30000           20.6              190.0
6  adelie  Torgersen        38.90000           17.8              181.0
7  adelie  Torgersen        39.20000           19.6              195.0
8  adelie  Torgersen        34.10000           18.1              193.0
9  adelie  Torgersen        42.00000           20.2              190.0

   body_mass_g      sex  body_mass_ounces
0       3750.0     Male           131.250
1       3800.0   Female           133.000
2       3250.0   Female           113.750
3          NaN  unknown               NaN
4       3450.0   Female           120.750
5       3650.0     Male           127.750
6       3625.0   Female           126.875
7       4675.0     Male           163.625
8       3475.0  unknown           121.625
9       4250.0  unknown           148.750   species              gentoo
island               Biscoe
bill_length_mm         45.2
bill_depth_mm          14.8
flipper_length_mm     212.0
body_mass_g          5200.0
sex                  Female
body_mass_ounces      182.0
Name: 342, dtype: object

## Challenge 04

### 4.1 Use `apply` on a DataFrame [1 pt]
Use `apply` to transform the values in the `species` column of `penguins` to lowercase.

In [23]:
# YOUR CODE HERE
penguins['species'] = penguins['species'].apply(lambda x: x.lower())

In [24]:
# hidden tests are within this cell
penguins.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,adelie,Torgersen,39.5,17.4,186.0,3800.0,Female

### 4.2 Write a custom function to transform data [1 pt]
Write a function `grams_to_ounces` that converts grams to ounces. For this calculation, use the conversion factor of 1 gram to 0.035 ounces.

In [25]:
# YOUR CODE HERE
def grams_to_ounces(grams):
    return grams * 0.035

In [26]:
# hidden tests are within this cell

### 4.3 `apply` a custom function to a DataFrame [1 pt]
Create a new column in `penguins`, `body_mass_ounces`, that is the result of passing the column `body_mass_g` through your custom function `grams_to_ounces`. You should use the `apply` method in pandas to do this.

In [27]:
# YOUR CODE HERE
penguins['body_mass_ounces'] = penguins['body_mass_g'].apply(lambda x: grams_to_ounces(x))

In [28]:
# hidden tests are within this cell
penguins.head(2)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_ounces
0,adelie,Torgersen,39.1,18.7,181.0,3750.0,Male,131.25
1,adelie,Torgersen,39.5,17.4,186.0,3800.0,Female,133.00

## Challenge 05

### 5.1 Filter a DataFrame by one condition [1 pt]
Create a new DataFrame, `biscoe_penguins`, that contains only penguins that live on Biscoe Island.

In [42]:
biscoe_penguins = penguins[penguins['island'] == 'Biscoe']

In [43]:
# hidden tests are within this cell
biscoe_penguins.head(5)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_ounces
20,adelie,Biscoe,37.8,18.3,174.0,3400.0,Female,119.00
21,adelie,Biscoe,37.7,18.7,180.0,3600.0,Male,126.00
22,adelie,Biscoe,35.9,19.2,189.0,3800.0,Female,133.00
23,adelie,Biscoe,38.2,18.1,185.0,3950.0,Male,138.25
24,adelie,Biscoe,38.8,17.2,180.0,3800.0,Male,133.00

### 5.2 Filter a Dataframe by multiple conditions [1 pt]
Create a new DataFrame, `big_dream_penguins`, that contains penguins who meet all of the following criteria: 

- They live on Dream Island
- They weigh more than 4000 grams
- Their flipper length is more than 200 mm

In [31]:
# YOUR CODE HERE
big_dream_penguins = penguins[(penguins['island'] == 'Dream') & (penguins['body_mass_g'] > 4000) & (penguins['flipper_length_mm'] > 200)]

In [32]:
# hidden tests are within this cell
big_dream_penguins.head(3)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_ounces
91,adelie,Dream,41.1,18.1,205.0,4300.0,Male,150.50
95,adelie,Dream,40.8,18.9,208.0,4300.0,Male,150.50
165,chinstrap,Dream,52.0,18.1,201.0,4050.0,Male,141.75

### 5.3 Count missing data [1 pt]
Count how many rows in `penguins` are missing data in the column `body_mass_g` and save this value as `n_missing_mass`.

In [33]:
# YOUR CODE HERE
n_missing_mass = penguins['body_mass_g'].isnull().sum()

In [34]:
# hidden tests are within this cell
n_missing_mass

np.int64(2)

### 5.4 Fill missing data with a fixed value [1 pt]
Replace any missing values in the columns `species` and `sex` with the string 'unknown'.

In [35]:
penguins[['species', 'sex']] = penguins[['species', 'sex']].fillna('unknown')

In [36]:
# hidden tests are within this cell

### 5.5 Fill missing data with a mean value [1 pt]
Calculate the mean value of `bill_length_mm` and assign it to the variable `mean_bill_length`. Then fill in any missing observations with the mean.

In [37]:
mean_bill_length = penguins['bill_length_mm'].mean()
penguins['bill_length_mm'] = penguins['bill_length_mm'].fillna(mean_bill_length)

In [38]:
# hidden tests are within this cell